POST http://localhost:8080/api/user/account/ACC14823111116/assign_role_app HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzM0MTc5MTgsImlkIjoiVVNSNTA3MjMxMTExMTYifQ.xq9aRJIN10dRpKQkFUrSjlH_zmwSw7rhv3mZ6o2Udnk

{
    "role_application":["Administrator"]
}