POST http://localhost:8080/api/user/USR81523101559/assign_role_app HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMzNzcxOTQsImlkIjoiVVNSODE1MjMxMDE1NTkifQ.W9HZkiC3lLkPYoi5nUzL4Y7XngNYxZdYwMDudZR3Mrs

{
    "role_application":["Admin"]
}