POST http://localhost:8080/api/article HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMzNjczNjcsImlkIjoiVVNSMTU0MjMxMDIyMTYifQ.i0QVQR_JhdGm_W60eKKDWQNxAT16hoelVb3zAoP8EEk

{
    "title":"New Article Pertama",
    "content":"Article Content Pertama"
}