POST http://localhost:8080/auth/register HTTP/1.1
content-type: application/json

{
    "role":["Administrator"],
    "application_id":"APP95523111115",
    "company_id":"COM85823111115",
    "email":"fajarsoegi@gmail.com",
    "username": "fajarsoegi",
    "password": "fajarsoegi1901"
}