POST http://localhost:8000/api/division HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMyNTQ3MTIsImlkIjoiVVNSNzE0MjM5MTQ1OCJ9.nF3WVc7-fi7S9p3TumbiJ5aB4KVYgdBRnirOp7zZ4_g

{
    "code":"DIV001",
    "name":"Divisi 1",
    "description":"DIVISI ESTATE 1",
    "estate_id":"EST1772391513"
}