POST http://localhost:8080/api/division HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMzNzc5MzIsImlkIjoiVVNSNDE4MjMxMDE2MTIifQ.vaJZjdq3vUGzbpUzkXTk88xoHJHhY2XLed-R7I5_u4w

{
    "name":"Divisi 2",
    "description":"DIVISI ESTATE 2",
    "estate_id":"EST20023101612"
}