POST http://localhost:8080/api/estate HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzM2MzEzOTAsImlkIjoiVVNSNTgzMjMxMzgyNSJ9.zks7j-2OVIqo8oeA0YHeNpdNp5j5G7OkaXcCQw4JGh8

{
    "code":"EST001",
    "name":"Estate 1",
    "description":"Description Estate 1",
    "company_id":"COMP120131231"
}