POST http://localhost:8080/api/estate HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMzNzc5MzIsImlkIjoiVVNSNDE4MjMxMDE2MTIifQ.vaJZjdq3vUGzbpUzkXTk88xoHJHhY2XLed-R7I5_u4w

{
    "code":"CODE102",
    "name":"Estate 2",
    "description":"Description Estate 2",
    "company_id":"COM39023101611"
}