// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplateapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Fajar soegi",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/application": {
            "get": {
                "description": "Get Application All",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(E) Application"
                ],
                "summary": "Get All Application",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schema.ApplicationResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(E) Application"
                ],
                "summary": "Create Application",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Estate Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestApplication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(E) Application"
                ],
                "summary": "Update Application",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Application Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestApplicationUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/application/{id}": {
            "get": {
                "description": "Get Application ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(E) Application"
                ],
                "summary": "Get Application By ID",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Application ID OR Application Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.ApplicationResponse"
                        }
                    }
                }
            }
        },
        "/company": {
            "get": {
                "description": "Get Company All",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(A) Company"
                ],
                "summary": "Get All Company",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schema.CompanyResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(A) Company"
                ],
                "summary": "Create Company",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Estate Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestCompany"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/company/{id}": {
            "get": {
                "description": "Get Company ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(A) Company"
                ],
                "summary": "Get Company By ID",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Company ID OR Company Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.CompanyResponse"
                        }
                    }
                }
            }
        },
        "/division": {
            "get": {
                "description": "Get Division All",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(C) Division"
                ],
                "summary": "Get All Division",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schema.DivisionResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Division",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(C) Division"
                ],
                "summary": "Create Division",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Estate Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestDivision"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Division",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(C) Division"
                ],
                "summary": "Update Division",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Company Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestDivisionUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/division/{id}": {
            "get": {
                "description": "Get Division ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(C) Division"
                ],
                "summary": "Get Division By ID",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Division ID OR Division Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.DivisionResponse"
                        }
                    }
                }
            }
        },
        "/employee": {
            "post": {
                "description": "Employee Create New",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Employee Add New",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Employee Add New Schema ",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.JsonEmployeeCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/employee/{id}": {
            "get": {
                "description": "Get Meta User By ID or Code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Get Meta User By ID or Code",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "USER ID OR USER Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MetaUser"
                        }
                    }
                }
            }
        },
        "/employee/{id}/edit": {
            "patch": {
                "description": "Employee Update Field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Employee Update",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Employee Update ",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.JsonEmployeeCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/estate": {
            "get": {
                "description": "Get Estate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(B) Estate"
                ],
                "summary": "Get Estate",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schema.EstateResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Estate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(B) Estate"
                ],
                "summary": "Create Estate",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Estate Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestEstate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(A) Company"
                ],
                "summary": "Update Company",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Company Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestCompanyUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/estate/{id}": {
            "get": {
                "description": "Get Estate ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(B) Estate"
                ],
                "summary": "Get Estate By ID",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Estate ID OR Estate Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.EstateResponse"
                        }
                    }
                }
            }
        },
        "/estate/{id}/edit": {
            "patch": {
                "description": "Update Estate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(B) Estate"
                ],
                "summary": "Update Field Estate",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Estate ID OR Estate Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Estate Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestEstateUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/gang": {
            "get": {
                "description": "Get Gang All",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(D) Gang"
                ],
                "summary": "Get All Gang",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schema.GangResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create Gang",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(D) Gang"
                ],
                "summary": "Create Gang",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Estate Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestGang"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Gang",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(D) Gang"
                ],
                "summary": "Update Gang",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Company Schema ",
                        "name": "Estate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.RequestGangUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        },
        "/gang/{id}": {
            "get": {
                "description": "Get Gang ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "(D) Gang"
                ],
                "summary": "Get Gang By ID",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Division ID OR Division Code",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.GangResponse"
                        }
                    }
                }
            }
        },
        "/user_new": {
            "post": {
                "description": "User New",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Credential"
                ],
                "summary": "User New",
                "parameters": [
                    {
                        "description": "Login Schema ",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.SignUpJsonSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.MsgResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "schema.ApplicationResponse": {
            "type": "object",
            "properties": {
                "app_package": {
                    "type": "string"
                },
                "app_package_class": {
                    "type": "string"
                },
                "asset_apk": {
                    "type": "string"
                },
                "asset_icon": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_note": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "schema.Company": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Employee"
                    }
                },
                "estates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Estate"
                    }
                },
                "fax": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "schema.CompanyResponse": {
            "type": "object",
            "required": [
                "address",
                "code",
                "description",
                "domain",
                "fax",
                "name",
                "phone_number",
                "sector"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Employee"
                    }
                },
                "estates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Estate"
                    }
                },
                "fax": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "schema.Division": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "estate_id": {
                    "type": "string"
                },
                "gangs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Gang"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "schema.DivisionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "estate_id": {
                    "type": "string"
                },
                "gang": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Gang"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Employee": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/schema.Company"
                },
                "company_id": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expiredAt": {
                    "type": "string"
                },
                "expired_time": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "office_number": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "schema.Estate": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/schema.Company"
                },
                "company_id": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "divisions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Division"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "schema.EstateResponse": {
            "type": "object",
            "properties": {
                "Division": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Division"
                    }
                },
                "code": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/schema.Company"
                },
                "delete": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.Gang": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "division": {
                    "$ref": "#/definitions/schema.Division"
                },
                "division_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.GangResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "division_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.JsonEmployeeCreate": {
            "type": "object",
            "required": [
                "address",
                "application",
                "code",
                "company_id",
                "department",
                "division",
                "email",
                "fullname",
                "nickname",
                "nik",
                "office_number",
                "password",
                "phone_number",
                "picture",
                "role",
                "role_application",
                "username"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "application": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "division": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "office_number": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "role": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "role_application": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "schema.MetaAccount": {
            "type": "object",
            "properties": {
                "application": {
                    "$ref": "#/definitions/schema.MetaApp"
                },
                "id": {
                    "type": "string"
                },
                "roleApplication": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaRoleApp"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "schema.MetaActivities": {
            "type": "object",
            "properties": {
                "application": {
                    "type": "string"
                },
                "client": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "pathOp": {
                    "type": "string"
                },
                "referrer": {
                    "type": "string"
                },
                "reqBody": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "schema.MetaApp": {
            "type": "object",
            "properties": {
                "appPackage": {
                    "type": "string"
                },
                "appPackageClass": {
                    "type": "string"
                },
                "assetApk": {
                    "type": "string"
                },
                "assetIcon": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedNote": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "schema.MetaCompany": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "schema.MetaDivision": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gang": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaGang"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.MetaEmployee": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/schema.MetaCompany"
                },
                "companyId": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expired": {
                    "type": "integer"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "officeNumber": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "schema.MetaEstate": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/schema.MetaCompany"
                },
                "description": {
                    "type": "string"
                },
                "division": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaDivision"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.MetaGang": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.MetaRoleApp": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.MetaRoles": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.MetaUser": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaAccount"
                    }
                },
                "activityLogs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaActivities"
                    }
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaEmployee"
                    }
                },
                "estates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaEstate"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.MetaRoles"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "schema.MsgResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "schema.RequestApplication": {
            "type": "object",
            "required": [
                "app_package",
                "app_package_class",
                "asset_apk",
                "asset_icon",
                "description",
                "name",
                "updated_note",
                "version"
            ],
            "properties": {
                "app_package": {
                    "type": "string"
                },
                "app_package_class": {
                    "type": "string"
                },
                "asset_apk": {
                    "type": "string"
                },
                "asset_icon": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_note": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "schema.RequestApplicationUpdate": {
            "type": "object",
            "required": [
                "app_package",
                "app_package_class",
                "asset_apk",
                "asset_icon",
                "delete",
                "description",
                "name",
                "status",
                "updated_note",
                "version"
            ],
            "properties": {
                "app_package": {
                    "type": "string"
                },
                "app_package_class": {
                    "type": "string"
                },
                "asset_apk": {
                    "type": "string"
                },
                "asset_icon": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updated_note": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "schema.RequestCompany": {
            "type": "object",
            "required": [
                "address",
                "code",
                "description",
                "domain",
                "fax",
                "name",
                "phone_number",
                "sector"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "schema.RequestCompanyUpdate": {
            "type": "object",
            "required": [
                "address",
                "code",
                "delete",
                "description",
                "domain",
                "fax",
                "name",
                "phone_number",
                "sector",
                "status"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.RequestDivision": {
            "type": "object",
            "required": [
                "code",
                "description",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "estate_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.RequestDivisionUpdate": {
            "type": "object",
            "required": [
                "code",
                "delete",
                "description",
                "name",
                "status"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "estate_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.RequestEstate": {
            "type": "object",
            "required": [
                "code",
                "company_id",
                "description",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.RequestEstateUpdate": {
            "type": "object",
            "required": [
                "code",
                "company_id",
                "delete",
                "description",
                "name",
                "status"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.RequestGang": {
            "type": "object",
            "required": [
                "code",
                "division_id",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "division_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schema.RequestGangUpdate": {
            "type": "object",
            "required": [
                "code",
                "delete",
                "division_id",
                "name",
                "status"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "division_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "schema.SignUpJsonSchema": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoapi holds exported Swagger Info so clients can modify it
var SwaggerInfoapi = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Swagger User Service",
	Description:      "This is User Service Test.",
	InfoInstanceName: "api",
	SwaggerTemplate:  docTemplateapi,
}

func init() {
	swag.Register(SwaggerInfoapi.InstanceName(), SwaggerInfoapi)
}
