// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplateauth = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Fajar soegi",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfoauth holds exported Swagger Info so clients can modify it
var SwaggerInfoauth = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/auth",
	Schemes:          []string{""},
	Title:            "Authentication User",
	Description:      "Authentication User Service.",
	InfoInstanceName: "auth",
	SwaggerTemplate:  docTemplateauth,
}

func init() {
	swag.Register(SwaggerInfoauth.InstanceName(), SwaggerInfoauth)
}
